### PR TITLE
Add interrupts

### PR DESCRIPTION
**Pull request by soundstorm**
This PR adds the ability to use interrupts.
Method naming may be adjusted.

I used arrays instead of if branches for the port mapping to reduce redundancy. We might refactor the code to make it more compact and all in the array format.

### CODE REVIEW

**Comment by CockpitConnect** [comment]
Tested this and seems okay to me. I've changed the example myself to use an interval with setInterval instead of using GPIO pin 4.

One question I do have is how we can ensure that an interrupt only occurs when a button is pushed (and no interrupt occurs when released). I've read the datasheet multiple times and think that enabling the INTEN (enable IOC) and INTCON (set IOC to compare with DEFVAL) registers by setting them to 0xff should compare the button value (bank A register will have value 0x10 when pressed) to the DEFVAL (value 0x00) register and only triggers the interrupt when the values differs to each other.
At the moment I couldn't get that working, releasing the button press will still lead to another interrupt. Does someone have a suggestion to this?

**Comment by soundstorm** [comment]
You can either trigger on a pin CHANGE (default) or a different value from DEFVAL, either LOW or HIGH, so as long as the button is pressed an interrupt will be generated. So there is no real way for falling or rising edge detection.

**Comment by soundstorm** [comment]
So as soon you read the capture or gpio register, the interrupt will be cleared, but if the button is still pressed you will see another interrupt.
With the gpio.watch this is easier to see, as you'll see a stream of interrupts while the state differs from DEFVAL.
Only way is to disable the Interrupt, then enable again after a timeout, but then you'll have that deadtime where no button presses will be registered at all.
Or just do it as I do, read the registers and discard if the state is not the one you wish for (simply trigger a `readPort(0, callback)` instead of the `getInterruptCapture(0, callback)`).

**Comment by kaihenzler** [comment]
@soundstorm thanks a lot for the PR!
I'm currently unable to test anything myself because I don't have any hardware to do so. Thanks @CockpitConnect for testing

**Comment by kaihenzler** [comment]
I have released version `0.1.0` on npm

**Pull request merged**
