### PR TITLE
Development

### PR DESCRIPTION
**Pull request by molda**

### CODE REVIEW

**Comment by kaihenzler** [comment]
Thanks a lot for the PR. The code looks alright. I wasn't aware that the Param of the send function was wrong. As I currently don’t have a mcp23017 I cannot test your changes but I’ll  trust you that it still works. 
Could you please add an example for the new methods you added or at least list them in the readme? That would be great, then I’ll release a new version

**Comment by molda** [comment]
Cool. I will add the examples. I have actualy only tested read methods so far. I will check the others too and fix it if needed.

**Comment by molda** [comment]
Hi, i have updated the readme and tested all the methods.
Everything seems to work fine.
I have also changed the version of i2c-bus 4.0.8 to 4.0.9 since there were no changes to functionality.

**Comment by kaihenzler** [comment]
@molda sorry for not responding. I actually made a mistake in the past and haven’t merged the latest master into the development branch, which is why I couldn’t integrate your changes yet into a new main version. I invested some time but I’m not completely done with the merge. I plan on finishing it next week. Sorry for the delay

**Comment by molda** [comment]
Cool and no worries. My setup works fine with my changes so i'm OK.

**Comment by vlturner** [comment]
Can you please update the i2c version to 0.5.5. Its no longer installing correctly on latest Debian "Buster" release on Raspberry Pi 4 4GB

**Comment by CockpitConnect** [comment]
This merge request should be merged. Tried this package and found out that the example code is incorrect (for the newer versions of the dependencies).

`device: '/dev/i2c-1'` should be `device: 1` (or 0 for model A). This merge request will change that.

Otherwise you'll get the error message `Invalid I2C bus number /dev/i2c-1`.

**Comment by soundstorm** [comment]
Can this be closed as it's outdated with 0.0.7 release?

**Pull request closed without merging**
